import type { Lang } from "./i18n";

const fr = {
  delivery: "Livraison et disponibilité", zones: "Communes / quartiers desservis", pickup: "Point de retrait public (facultatif)",
  days: "Délai annoncé en jours", fees: "Frais de remise", included: "Inclus dans le prix affiché", quote: "À confirmer avec le vendeur avant paiement",
  next: "Prochaine disponibilité", confirm: "Je viens de vérifier la disponibilité", confirmed: "Disponibilité déclarée par le vendeur le", unknown: "Disponibilité à confirmer avec le vendeur",
  reminder: "Pensez à revérifier le stock ou votre prochain créneau avant de confirmer.", save: "Enregistrer", saving: "Enregistrement…", saved: "Enregistré", error: "Impossible d’enregistrer. Votre saisie est conservée ; vérifiez la connexion et réessayez.",
  ask: "Confirmer le lieu, les frais et le délai avec le vendeur", checkPay: "Vérifier et payer", missing: "Informations de remise non renseignées : contactez le vendeur avant de payer.",
  publicHint: "Ces informations sont publiques. Indiquez un point de retrait commercial, jamais une adresse privée. Les frais inclus font partie du prix du produit ; aucun supplément n’est ajouté ici.",
  offlineTitle: "Offres récemment consultées", offlineHint: "Copies enregistrées sur cet appareil pendant 7 jours. Les prix et stocks peuvent avoir changé. Une connexion est nécessaire pour vérifier et acheter.",
  empty: "Aucune offre enregistrée sur cet appareil.", viewed: "Consulté le", refresh: "Ouvrir et vérifier en ligne", erase: "Effacer les offres enregistrées", search: "Rechercher dans les offres enregistrées",
  disconnected: "Vous êtes hors ligne. Vos saisies restent dans cette page. Aucun paiement ne peut être confirmé sans connexion.", reconnect: "Connexion rétablie. Vérifiez le statut dans Mes achats avant de repayer.", offlineLink: "Voir les offres enregistrées",
  help: "J’ai besoin d’aide", debited: "Paiement débité, commande non confirmée", notReceived: "Article non reçu", wrong: "Article reçu incorrect", order: "Commande", sendSeller: "Écrire au vendeur", contact: "Contacter Zabelie", copy: "Copier la demande", copied: "Demande copiée", copyHint: "Copiez cette demande puis collez-la dans le canal d’aide. Elle contient la référence de commande, jamais votre code PIN.",
  helpNote: "Ce message ne remplace pas le bouton « Je n’ai pas reçu » lorsqu’il est disponible. Celui-ci signale officiellement la contestation.",
  statusNote: "Ces indications reflètent la configuration et le catalogue. Elles ne garantissent pas la disponibilité instantanée de l’opérateur.",
  topupClosed: "Recharges temporairement indisponibles", topupTest: "Recharges en test : aucun crédit réel", topupReady: "Recharges configurées", topupWhy: "La livraison de crédit n’est pas encore prête. Consultez l’aide pour les services disponibles.",
  resume: "Vérifier ma commande", draft: "Saisie conservée dans cet onglet pendant 30 minutes. Vérifiez les informations avant de payer.",
};
export type MarketplaceCopy = typeof fr;
const ht: MarketplaceCopy = {
  delivery: "Livrezon ak disponiblite", zones: "Komin / katye nou sèvi", pickup: "Pwen retrè piblik (si genyen)", days: "Delè anonse an jou", fees: "Frè remiz", included: "Enkli nan pri ki parèt la", quote: "Konfime ak vandè a anvan ou peye",
  next: "Pwochen disponibilite", confirm: "Mwen fèk verifye disponiblite a", confirmed: "Vandè a deklare disponiblite a nan dat", unknown: "Konfime disponiblite a ak vandè a", reminder: "Verifye estòk la oswa pwochen lè ou disponib anvan ou konfime.", save: "Anrejistre", saving: "N ap anrejistre…", saved: "Anrejistre", error: "Nou pa ka anrejistre. Sa ou ekri a rete la ; verifye koneksyon an epi eseye ankò.",
  ask: "Konfime kote, frè ak delè a ak vandè a", checkPay: "Verifye epi peye", missing: "Enfòmasyon sou remiz la poko la : kontakte vandè a anvan ou peye.", publicHint: "Enfòmasyon sa yo piblik. Mete yon pwen retrè komèsyal, pa yon adrès prive. Frè ki enkli yo fè pati pri pwodwi a ; nou pa ajoute frè isit la.",
  offlineTitle: "Òf ou te gade dènyèman", offlineHint: "Kopi yo rete sou aparèy sa a pandan 7 jou. Pri ak estòk ka chanje. Ou bezwen entènèt pou verifye epi achte.", empty: "Pa gen òf anrejistre sou aparèy sa a.", viewed: "Ou te gade l nan dat", refresh: "Louvri epi verifye sou entènèt", erase: "Efase òf anrejistre yo", search: "Chèche nan òf anrejistre yo",
  disconnected: "Ou pa sou entènèt. Sa ou ekri yo rete nan paj sa a. Nou pa ka konfime okenn peman san koneksyon.", reconnect: "Entènèt la retounen. Verifye estati a nan Acha mwen anvan ou peye ankò.", offlineLink: "Gade òf anrejistre yo",
  help: "Mwen bezwen èd", debited: "Lajan soti, kòmann pa konfime", notReceived: "Mwen pa resevwa atik la", wrong: "Mwen resevwa move atik la", order: "Kòmann", sendSeller: "Ekri vandè a", contact: "Kontakte Zabelie", copy: "Kopye demann nan", copied: "Demann nan kopye", copyHint: "Kopye demann sa a epi kole l nan kanal èd la. Li gen referans kòmann nan, pa janm kòd PIN ou.", helpNote: "Mesaj sa a pa ranplase bouton « Mwen pa resevwa » lè li disponib. Se bouton sa a ki deklare kontestasyon an ofisyèlman.",
  statusNote: "Endikasyon sa yo baze sou konfigirasyon ak katalòg la. Yo pa garanti operatè a disponib nan moman an.", topupClosed: "Rechaj pa disponib pou kounye a", topupTest: "Rechaj an tès : pa gen kredi reyèl", topupReady: "Rechaj konfigire", topupWhy: "Livrezon kredi a poko pare. Gade èd pou sèvis ki disponib yo.", resume: "Verifye kòmann mwen", draft: "Sa ou ekri yo rete nan onglet sa a pandan 30 minit. Verifye yo anvan ou peye.",
};
const en: MarketplaceCopy = {
  delivery: "Delivery and availability", zones: "Communes / neighbourhoods served", pickup: "Public pickup point (optional)", days: "Estimated delivery days", fees: "Handover fees", included: "Included in the displayed price", quote: "Confirm with the seller before paying", next: "Next availability", confirm: "I have just checked availability", confirmed: "Availability reported by the seller on", unknown: "Confirm availability with the seller", reminder: "Recheck stock or your next available slot before confirming.", save: "Save", saving: "Saving…", saved: "Saved", error: "Could not save. Your input is preserved; check your connection and try again.", ask: "Confirm location, fees and timing with the seller", checkPay: "Review and pay", missing: "Handover details are missing: contact the seller before paying.", publicHint: "These details are public. Use a commercial pickup point, never a private address. Included fees are part of the product price; no surcharge is added here.",
  offlineTitle: "Recently viewed offers", offlineHint: "Copies stay on this device for 7 days. Prices and stock may have changed. Connect to verify and buy.", empty: "No offers saved on this device.", viewed: "Viewed on", refresh: "Open and check online", erase: "Clear saved offers", search: "Search saved offers", disconnected: "You are offline. Your input stays on this page. Payments cannot be confirmed without a connection.", reconnect: "Connection restored. Check My purchases before paying again.", offlineLink: "View saved offers", help: "I need help", debited: "Payment debited, order not confirmed", notReceived: "Item not received", wrong: "Wrong item received", order: "Order", sendSeller: "Message the seller", contact: "Contact Zabelie", copy: "Copy request", copied: "Request copied", copyHint: "Copy this request and paste it in the support channel. It contains the order reference, never your PIN.", helpNote: "This message does not replace the “Not received” button when available. That button formally raises the dispute.", statusNote: "These indicators reflect configuration and catalogue checks. They do not guarantee the provider’s current availability.", topupClosed: "Top-ups temporarily unavailable", topupTest: "Test top-ups: no real credit", topupReady: "Top-ups configured", topupWhy: "Credit delivery is not ready yet. Check help for available services.", resume: "Check my order", draft: "Input stays in this tab for 30 minutes. Check it before paying.",
};
const es: MarketplaceCopy = {
  delivery: "Entrega y disponibilidad", zones: "Comunas / barrios atendidos", pickup: "Punto de recogida público (opcional)", days: "Plazo anunciado en días", fees: "Gastos de entrega", included: "Incluidos en el precio mostrado", quote: "Confirmar con el vendedor antes de pagar", next: "Próxima disponibilidad", confirm: "Acabo de comprobar la disponibilidad", confirmed: "Disponibilidad declarada por el vendedor el", unknown: "Confirma la disponibilidad con el vendedor", reminder: "Comprueba las existencias o tu próxima disponibilidad antes de confirmar.", save: "Guardar", saving: "Guardando…", saved: "Guardado", error: "No se pudo guardar. Tus datos se conservan; comprueba la conexión e inténtalo de nuevo.", ask: "Confirmar lugar, gastos y plazo con el vendedor", checkPay: "Revisar y pagar", missing: "Faltan detalles de entrega: contacta al vendedor antes de pagar.", publicHint: "Estos datos son públicos. Indica un punto comercial de recogida, nunca una dirección privada. Los gastos incluidos forman parte del precio; aquí no se añade ningún recargo.",
  offlineTitle: "Ofertas vistas recientemente", offlineHint: "Las copias se guardan en este dispositivo durante 7 días. Los precios y existencias pueden cambiar. Conéctate para comprobar y comprar.", empty: "No hay ofertas guardadas en este dispositivo.", viewed: "Consultado el", refresh: "Abrir y comprobar en línea", erase: "Borrar ofertas guardadas", search: "Buscar en ofertas guardadas", disconnected: "Sin conexión. Tus datos permanecen en esta página. No se puede confirmar ningún pago sin conexión.", reconnect: "Conexión restablecida. Consulta Mis compras antes de volver a pagar.", offlineLink: "Ver ofertas guardadas", help: "Necesito ayuda", debited: "Pago cobrado, pedido sin confirmar", notReceived: "Artículo no recibido", wrong: "Artículo recibido incorrecto", order: "Pedido", sendSeller: "Escribir al vendedor", contact: "Contactar a Zabelie", copy: "Copiar solicitud", copied: "Solicitud copiada", copyHint: "Copia esta solicitud y pégala en el canal de ayuda. Incluye la referencia del pedido, nunca tu PIN.", helpNote: "Este mensaje no sustituye el botón « No recibido » cuando está disponible. Ese botón presenta la reclamación formal.", statusNote: "Estos indicadores reflejan la configuración y el catálogo. No garantizan la disponibilidad inmediata del operador.", topupClosed: "Recargas temporalmente no disponibles", topupTest: "Recargas de prueba: sin crédito real", topupReady: "Recargas configuradas", topupWhy: "La entrega de crédito aún no está lista. Consulta la ayuda para ver los servicios disponibles.", resume: "Consultar mi pedido", draft: "Los datos se conservan en esta pestaña durante 30 minutos. Revísalos antes de pagar.",
};
export function marketplaceCopy(lang: Lang): MarketplaceCopy { return { fr, ht, en, es }[lang]; }
