import type { Lang } from "@/lib/i18n";

const fr = {
  type: "Type d’offre", allTypes: "Tous les types", digitalNote: "Vérifiez les formats, la licence et les conditions d’accès au fichier sur la fiche.",
  title: "Assistant d’achat Zabelie", sellerTitle: "Le vendeur IA de cette boutique",
  intro: "Décrivez votre recherche. Comparez jusqu’à trois offres du catalogue, selon votre besoin et votre budget.",
  query: "Quel produit ou service cherchez-vous ?", budgetHtg: "Quel est votre budget maximum en HTG ?",
  need: "À quoi servira votre achat ?", location: "Dans quelle ville ou localité êtes-vous ?",
  send: "Envoyer", message: "Votre réponse", searching: "Recherche en cours…", guided: "Recherche guidée",
  guidedNote: "Vous pouvez aussi renseigner directement vos critères.", search: "Comparer les offres", reset: "Nouvelle recherche",
  results: "Les offres à comparer", empty: "Aucune offre disponible ne correspond à ces critères. Essayez un terme plus précis ou ajustez votre budget.",
  shortlist: "Sélection parmi les offres récentes correspondant à votre recherche. Le classement privilégie la pertinence, puis les avis et le prix.",
  sellerFacts: "Description du vendeur", noDescription: "Le vendeur n’a pas fourni de description.",
  matches: "Correspondances dans la fiche", price: "Prix de référence", from: "À partir de", difference: "Écart par rapport au premier choix", reviews: "Avis", noReviews: "Aucun avis",
  choose: "Choisir et payer", details: "Vérifier la fiche, les options et les moyens de paiement disponibles.",
  handover: "La remise et une éventuelle livraison sont organisées par le vendeur. Votre localité ne confirme pas une zone desservie ; vérifiez les conditions sur la fiche.",
  finalPrice: "Le prix final, les promotions et le stock sont vérifiés dans le parcours de paiement existant.",
  error: "Assistant indisponible. Réessayez plus tard ou consultez le catalogue.", limit: "Trop de demandes. Réessayez plus tard.",
  catalog: "Voir le catalogue", add: "Ajouter au panier", adding: "Ajout…", added: "Ajouté", seeCart: "Voir le panier", signin: "Se connecter",
  chatUnavailable: "Le dialogue IA sera disponible lorsque le fournisseur sera activé. La recherche guidée reste accessible.",
  privacy: "Évitez les données sensibles. Le texte du dialogue est transmis au fournisseur IA configuré ; aucune conversation n’est enregistrée par cet assistant.",
};
export type ShoppingCopy = typeof fr;
const ht: ShoppingCopy = {
  type: "Kalite òf", allTypes: "Tout kalite", digitalNote: "Verifye fòma, lisans ak kondisyon aksè fichye a sou fich pwodui a.",
  title: "Asistan acha Zabelie", sellerTitle: "Vandè IA boutik sa a",
  intro: "Di sa w ap chèche. Konpare jiska twa òf nan katalòg la selon bezwen w ak bidjè w.",
  query: "Ki pwodui oswa sèvis w ap chèche ?", budgetHtg: "Ki bidjè maksimòm ou an goud ?",
  need: "Pou kisa w pral itilize sa w ap achte a ?", location: "Nan ki vil oswa lokalite ou ye ?",
  send: "Voye", message: "Repons ou", searching: "N ap chèche…", guided: "Rechèch gide",
  guidedNote: "Ou ka ranpli kritè ou yo dirèkteman tou.", search: "Konpare òf yo", reset: "Nouvo rechèch",
  results: "Òf pou konpare", empty: "Pa gen òf disponib ki koresponn ak kritè sa yo. Eseye yon mo pi presi oswa ajiste bidjè w.",
  shortlist: "Seleksyon nan òf resan ki koresponn ak rechèch ou. Klasman an bay bezwen w priyorite, apre sa avi ak pri.",
  sellerFacts: "Deskripsyon vandè a", noDescription: "Vandè a pa bay deskripsyon.",
  matches: "Mo ki koresponn nan fich la", price: "Pri referans", from: "Apati", difference: "Diferans ak premye chwa a", reviews: "Avi", noReviews: "Pa gen avi",
  choose: "Chwazi epi peye", details: "Verifye fich la, opsyon yo ak mwayen peman ki disponib yo.",
  handover: "Se vandè a ki òganize remiz la ak livrezon si genyen. Lokalizasyon ou pa konfime zòn li sèvi ; verifye kondisyon sou fich la.",
  finalPrice: "Pri final la, pwomosyon ak estòk verifye nan pwosesis peman ki egziste deja a.",
  error: "Asistan an pa disponib. Eseye pita oswa ale nan katalòg la.", limit: "Twòp demann. Eseye pita.",
  catalog: "Gade katalòg la", add: "Ajoute nan panyen", adding: "N ap ajoute…", added: "Ajoute", seeCart: "Gade panyen", signin: "Konekte",
  chatUnavailable: "Dyalòg IA ap disponib lè founisè a aktive. Rechèch gide toujou aksesib.",
  privacy: "Pa bay done sansib. Tèks dyalòg la ale bay founisè IA ki konfigire a ; asistan sa a pa anrejistre okenn konvèsasyon.",
};
const en: ShoppingCopy = {
  type: "Offer type", allTypes: "All types", digitalNote: "Check file formats, license and access conditions on the listing.",
  title: "Zabelie shopping assistant", sellerTitle: "This shop’s AI seller",
  intro: "Describe what you are looking for. Compare up to three catalogue offers based on your needs and budget.",
  query: "What product or service are you looking for?", budgetHtg: "What is your maximum budget in HTG?",
  need: "How will you use your purchase?", location: "What city or locality are you in?",
  send: "Send", message: "Your answer", searching: "Searching…", guided: "Guided search",
  guidedNote: "You can also enter your criteria directly.", search: "Compare offers", reset: "New search",
  results: "Offers to compare", empty: "No available offers match these criteria. Try a more specific search term or adjust your budget.",
  shortlist: "Selected from recent offers matching your search. Ranking prioritizes relevance, then reviews and price.",
  sellerFacts: "Seller description", noDescription: "The seller has not provided a description.",
  matches: "Matching terms in the listing", price: "Reference price", from: "From", difference: "Difference from the first choice", reviews: "Reviews", noReviews: "No reviews",
  choose: "Choose and pay", details: "Check the listing, options and available payment methods.",
  handover: "The seller arranges handover and any delivery. Your locality does not confirm service coverage; check the listing’s terms.",
  finalPrice: "The final price, promotions and stock are checked in the existing payment process.",
  error: "Assistant unavailable. Try again later or browse the catalogue.", limit: "Too many requests. Try again later.",
  catalog: "Browse catalogue", add: "Add to cart", adding: "Adding…", added: "Added", seeCart: "View cart", signin: "Sign in",
  chatUnavailable: "AI chat will be available once the provider is enabled. Guided search is still available.",
  privacy: "Avoid sensitive data. Chat text is sent to the configured AI provider; this assistant does not store conversations.",
};
const es: ShoppingCopy = {
  type: "Tipo de oferta", allTypes: "Todos los tipos", digitalNote: "Comprueba los formatos, la licencia y las condiciones de acceso al archivo en la ficha.",
  title: "Asistente de compras Zabelie", sellerTitle: "El vendedor IA de esta tienda",
  intro: "Describe lo que buscas. Compara hasta tres ofertas del catálogo según tus necesidades y presupuesto.",
  query: "¿Qué producto o servicio buscas?", budgetHtg: "¿Cuál es tu presupuesto máximo en HTG?",
  need: "¿Para qué usarás tu compra?", location: "¿En qué ciudad o localidad estás?",
  send: "Enviar", message: "Tu respuesta", searching: "Buscando…", guided: "Búsqueda guiada",
  guidedNote: "También puedes introducir tus criterios directamente.", search: "Comparar ofertas", reset: "Nueva búsqueda",
  results: "Ofertas para comparar", empty: "No hay ofertas disponibles que coincidan. Prueba un término más preciso o ajusta tu presupuesto.",
  shortlist: "Selección de ofertas recientes que coinciden con tu búsqueda. La clasificación prioriza pertinencia, opiniones y precio.",
  sellerFacts: "Descripción del vendedor", noDescription: "El vendedor no ha proporcionado una descripción.",
  matches: "Coincidencias en la ficha", price: "Precio de referencia", from: "Desde", difference: "Diferencia respecto a la primera opción", reviews: "Opiniones", noReviews: "Sin opiniones",
  choose: "Elegir y pagar", details: "Comprueba la ficha, las opciones y los métodos de pago disponibles.",
  handover: "El vendedor organiza la entrega y cualquier envío. Tu localidad no confirma cobertura; revisa las condiciones de la ficha.",
  finalPrice: "El precio final, las promociones y las existencias se verifican en el proceso de pago existente.",
  error: "Asistente no disponible. Inténtalo más tarde o consulta el catálogo.", limit: "Demasiadas solicitudes. Inténtalo más tarde.",
  catalog: "Ver catálogo", add: "Añadir al carrito", adding: "Añadiendo…", added: "Añadido", seeCart: "Ver carrito", signin: "Iniciar sesión",
  chatUnavailable: "El diálogo IA estará disponible cuando se active el proveedor. La búsqueda guiada sigue disponible.",
  privacy: "Evita datos sensibles. El texto del diálogo se envía al proveedor IA configurado; este asistente no guarda conversaciones.",
};
export const SHOPPING_COPY: Record<Lang, ShoppingCopy> = { fr, ht, en, es };
