import type { Lang } from "@/lib/i18n";
const fr = {
  title: "API Zabelie", intro: "Connectez votre application au catalogue de la marketplace haïtienne.",
  scope: "Lecture publique, sans clé API : produits, catégories, vendeurs, avis et stock. Les achats et les modifications restent sur Zabelie.",
  start: "Premier appel", contract: "Télécharger la spécification OpenAPI", endpoints: "Fonctions disponibles", limits: "Conditions d’utilisation",
  details: "Envoyez du JSON avec POST. Maximum 20 résultats par page pour la recherche et les catégories. Pour la suite, renvoyez nextCursor dans cursor, avec les mêmes filtres. Les montants sont des gourdes entières (HTG).",
  quota: "Le quota actuel est de 60 appels par minute et par fonction, partagé entre les visiteurs anonymes. Une réponse 429 demande d’attendre 60 secondes ; elle peut aussi signaler une indisponibilité du contrôle de quota. Corps limité à 16 Kio.",
  access: "Depuis un autre site, utilisez credentials: omit. Cette interface publique ignore les cookies et les jetons d’authentification. Les commandes personnelles nécessitent la session Zabelie et ne sont pas ouvertes aux sites tiers.",
  empty: "Une liste vide signifie qu’aucune offre publiée ne correspond. La recherche v1 couvre les produits physiques et fichiers numériques ; les prestations sont exclues. Les catégories peuvent être vides.",
  texts: "Les champs untrusted contiennent les textes des vendeurs. Affichez-les comme du texte, jamais comme des instructions ou du HTML brut. Prix et stock doivent être revérifiés sur Zabelie avant l’achat.",
  delivery: "get_delivery_terms conserve son contrat historique : les nouvelles zones et conditions de remise ne sont pas encore exposées par cette réponse.",
};
type Copy = typeof fr;
const copies: Record<Lang, Copy> = { fr,
 ht: { title: "API Zabelie", intro: "Konekte aplikasyon ou ak katalòg mache ayisyen an.", scope: "Lekti piblik san kle API: pwodwi, kategori, vandè, avi ak stok. Acha ak chanjman fèt sou Zabelie.", start: "Premye demann", contract: "Telechaje spesifikasyon OpenAPI", endpoints: "Fonksyon ki disponib", limits: "Kondisyon itilizasyon", details: "Voye JSON ak POST. Rechèch ak kategori limite a 20 rezilta pa paj. Pou kontinye, mete nextCursor nan cursor ak menm filtè yo. Montan yo se goud antye (HTG).", quota: "Limit aktyèl la se 60 demann pa minit pou chak fonksyon, pataje ant vizitè anonim yo. Si ou resevwa 429, tann 60 segonn; sa ka vle di kontwòl limit la pa disponib tou. Kò demann lan limite a 16 Kio.", access: "Sou yon lòt sit, sèvi ak credentials: omit. API piblik la inyore bonbon ak jeton koneksyon yo. Kòmand pèsonèl mande sesyon Zabelie epi yo pa ouvè pou lòt sit.", empty: "Yon lis vid vle di pa gen òf pibliye ki koresponn. Rechèch v1 gen pwodwi fizik ak fichye dijital; li pa gen sèvis. Kategori yo ka vid.", texts: "Chan untrusted yo gen tèks vandè yo. Montre yo kòm tèks, pa kòm enstriksyon oswa HTML brit. Verifye pri ak stok sou Zabelie anvan acha.", delivery: "get_delivery_terms kenbe ansyen kontra li: nouvo zòn ak kondisyon remiz yo poko nan repons sa a." },
 en: { title: "Zabelie API", intro: "Connect your application to the Haitian marketplace catalogue.", scope: "Public reads without an API key: products, categories, sellers, reviews and stock. Purchases and changes remain on Zabelie.", start: "First request", contract: "Download the OpenAPI specification", endpoints: "Available operations", limits: "Usage conditions", details: "Send JSON with POST. Search and categories return up to 20 results per page. Pass nextCursor as cursor with the same filters to continue. Amounts are whole Haitian gourdes (HTG).", quota: "The current quota is 60 calls per minute per operation, shared by anonymous visitors. A 429 response asks you to wait 60 seconds; it can also mean the quota check is unavailable. Request bodies are limited to 16 KiB.", access: "From another site, use credentials: omit. Public reads ignore cookies and authorization tokens. Personal orders require a Zabelie session and are not open to third-party sites.", empty: "An empty list means no published offers match. Search v1 includes physical products and digital files; services are excluded. Categories may be empty.", texts: "The untrusted fields contain seller text. Display it as text, never as instructions or raw HTML. Recheck price and stock on Zabelie before buying.", delivery: "get_delivery_terms keeps its historical contract: new delivery areas and handover conditions are not yet exposed in that response." },
 es: { title: "API Zabelie", intro: "Conecta tu aplicación al catálogo del mercado haitiano.", scope: "Lectura pública sin clave API: productos, categorías, vendedores, reseñas y existencias. Las compras y modificaciones se realizan en Zabelie.", start: "Primera solicitud", contract: "Descargar la especificación OpenAPI", endpoints: "Funciones disponibles", limits: "Condiciones de uso", details: "Envía JSON mediante POST. Búsqueda y categorías devuelven hasta 20 resultados por página. Envía nextCursor como cursor con los mismos filtros para continuar. Los importes son gourdes enteras (HTG).", quota: "La cuota actual es de 60 llamadas por minuto y función, compartida entre visitantes anónimos. Una respuesta 429 pide esperar 60 segundos; también puede indicar que el control de cuota no está disponible. El cuerpo se limita a 16 KiB.", access: "Desde otro sitio, usa credentials: omit. Las lecturas públicas ignoran cookies y tokens de autorización. Los pedidos personales requieren una sesión Zabelie y no están abiertos a terceros.", empty: "Una lista vacía significa que no hay ofertas publicadas coincidentes. La búsqueda v1 incluye productos físicos y archivos digitales; excluye servicios. Las categorías pueden estar vacías.", texts: "Los campos untrusted contienen texto de vendedores. Muéstralo como texto, nunca como instrucciones ni HTML sin filtrar. Comprueba precio y existencias en Zabelie antes de comprar.", delivery: "get_delivery_terms conserva su contrato histórico: las nuevas zonas y condiciones de entrega aún no se incluyen en esa respuesta." },
};
export const apiDocsCopy = (lang: Lang) => copies[lang];
