select zabelie_migration_garde('0077_taxonomie_niveau3.sql');

-- ============================================================================
-- 0077 — TAXONOMIE NIVEAU 3 : le seed complet, DORMANT (V-3, docs/35)
-- ============================================================================
-- Arbitrage porteur du 2026-08-15 : « ok pour tout seeder et activer par
-- vagues ». Conforme à docs/16 (activation par vagues, décision 2026-07-24) :
-- TOUT le niveau 3 du document entre en base, `active = false` — un rayon
-- s'ouvre ensuite par UPDATE, sans migration. Un nœud inactif n'apparaît ni
-- à la publication ni dans les filtres (0035).
--
-- Libellés FR = docs/16 (qui fait foi) ; KR et EN produits par l'agent,
-- BEST-EFFORT, EN ATTENTE DE RELECTURE NATIVE — même statut que le seed des
-- zones (0069) et l'i18n. Slugs dérivés du kreyòl (convention 0035),
-- anti-collision déterministe par suffixe de parent.
--
-- `on conflict (slug) do nothing` : les ~45 sous-catégories de la vague 1
-- déjà en base gardent leur ligne (et leur état actif) — ce seed n'écrase
-- RIEN. 16.3 (Digicel/Natcom) exclu : catalogue Reloadly, non éditable.
-- ============================================================================

with p as (select id, slug from zabelie_categories where level = 2)
insert into zabelie_categories (parent_id, level, slug, label_fr, label_kr, label_en, active, position)
select p.id, 3, v.slug, v.fr, v.kr, v.en, false, v.pos
  from (values
  ('pyes-detache-oto', 'mote', 'Moteur (culasse, joints, pistons, courroies)', 'Motè (kilas, jwen, piston, kouwa)', 'Engine (head, gaskets, pistons, belts)', 10),
  ('pyes-detache-oto', 'frenaj', 'Freinage (plaquettes, disques, étriers, liquide)', 'Frenaj (plakèt, disk, etriye)', 'Brakes (pads, discs, calipers, fluid)', 20),
  ('pyes-detache-oto', 'sispansyon-direksyon', 'Suspension & direction', 'Sispansyon & direksyon', 'Suspension & steering', 30),
  ('pyes-detache-oto', 'anbreyaj-transmisyon', 'Embrayage & transmission', 'Anbreyaj & transmisyon', 'Clutch & transmission', 40),
  ('pyes-detache-oto', 'filtrasyon', 'Filtration (huile, air, carburant, habitacle)', 'Filtrasyon', 'Filtration', 50),
  ('pyes-detache-oto', 'demaraj-chaj', 'Démarrage & charge (batteries, alternateurs, démarreurs, bougies)', 'Demaraj & chaj (batri, altènatè)', 'Starting & charging', 60),
  ('pyes-detache-oto', 'refwadisman', 'Refroidissement (radiateurs, pompes à eau, thermostats)', 'Refwadisman (radyatè, ponp dlo)', 'Cooling', 70),
  ('pyes-detache-oto', 'echapman', 'Échappement', 'Echapman', 'Exhaust', 80),
  ('pyes-detache-oto', 'kawosri', 'Carrosserie (pare-chocs, ailes, capots, phares, feux)', 'Kawosri (parechòk, zèl, kapo, limyè)', 'Body (bumpers, fenders, hoods, lights)', 90),
  ('pyes-detache-oto', 'vitraj-retwovize', 'Vitrage & rétroviseurs', 'Vitraj & retwovizè', 'Glass & mirrors', 100),
  ('pyes-detache-oto', 'elektrisite-kablaj', 'Électricité & câblage', 'Elektrisite & kablaj', 'Electrical & wiring', 110),
  ('pyes-detache-oto', 'klimatizasyon', 'Climatisation', 'Klimatizasyon', 'Air conditioning', 120),
  ('pyes-detache-moto', 'mote-moto', 'Moteur moto', 'Motè moto', 'Motorcycle engine', 10),
  ('pyes-detache-moto', 'frenaj-moto', 'Freinage moto', 'Frenaj moto', 'Motorcycle brakes', 20),
  ('pyes-detache-moto', 'chen-pinyon-kouwon', 'Chaînes, pignons & couronnes', 'Chèn, pinyon & kouwòn', 'Chains & sprockets', 30),
  ('pyes-detache-moto', 'sispansyon-moto', 'Suspension moto', 'Sispansyon moto', 'Motorcycle suspension', 40),
  ('pyes-detache-moto', 'karenaj-kawosri', 'Carénage & carrosserie', 'Karenaj & kawosri', 'Fairings & bodywork', 50),
  ('pyes-detache-moto', 'batri-moto', 'Batteries moto', 'Batri moto', 'Motorcycle batteries', 60),
  ('pyes-detache-moto', 'bouji-alimaj', 'Bougies & allumage', 'Bouji & alimaj', 'Spark plugs & ignition', 70),
  ('pyes-detache-moto', 'kab-komand', 'Câbles & commandes', 'Kab & kòmand', 'Cables & controls', 80),
  ('pyes-detache-moto', 'gidon-levye-repoze-pye', 'Guidons, leviers & repose-pieds', 'Gidon, levye & repoze-pye', 'Handlebars, levers & footpegs', 90),
  ('pyes-detache-moto', 'echapman-moto', 'Échappement moto', 'Echapman moto', 'Motorcycle exhaust', 100),
  ('kawotchou-jant', 'kawotchou-oto', 'Pneus auto', 'Kawotchou oto', 'Car tires', 10),
  ('kawotchou-jant', 'kawotchou-moto', 'Pneus moto', 'Kawotchou moto', 'Motorcycle tires', 20),
  ('kawotchou-jant', 'kawotchou-kamyon-pickop', 'Pneus camion & pick-up', 'Kawotchou kamyon & pickòp', 'Truck & pickup tires', 30),
  ('kawotchou-jant', 'jant-anjolive', 'Jantes & enjoliveurs', 'Jant & anjolivè', 'Rims & hubcaps', 40),
  ('kawotchou-jant', 'chanm-a-le', 'Chambres à air', 'Chanm a lè', 'Inner tubes', 50),
  ('kawotchou-jant', 'valv-ekilibraj', 'Valves & équilibrage', 'Valv & ekilibraj', 'Valves & balancing', 60),
  ('kawotchou-jant', 'kit-anti-krevezon', 'Kits anti-crevaison', 'Kit anti-krevezon', 'Puncture repair kits', 70),
  ('luil-likid', 'luil-mote', 'Huile moteur', 'Luil motè', 'Engine oil', 10),
  ('luil-likid', 'luil-bwat', 'Huile de boîte', 'Luil bwat', 'Gearbox oil', 20),
  ('luil-likid', 'likid-fren', 'Liquide de frein', 'Likid fren', 'Brake fluid', 30),
  ('luil-likid', 'likid-refwadisman', 'Liquide de refroidissement', 'Likid refwadisman', 'Coolant', 40),
  ('luil-likid', 'likid-lavwit', 'Liquide lave-glace', 'Likid lavwit', 'Washer fluid', 50),
  ('luil-likid', 'gres', 'Graisses', 'Grès', 'Greases', 60),
  ('luil-likid', 'aditif-tretman', 'Additifs & traitements', 'Aditif & tretman', 'Additives & treatments', 70),
  ('akseswa-oto', 'tapi-fouwo-chez', 'Tapis & housses de siège', 'Tapi & fouwo chèz', 'Mats & seat covers', 10),
  ('akseswa-oto', 'otoradyo-miltimedya', 'Autoradio & multimédia', 'Otoradyo & miltimedya', 'Car audio & multimedia', 20),
  ('akseswa-oto', 'kamera-rekil-asistans', 'Caméras de recul & assistance', 'Kamera rekil & asistans', 'Backup cameras & assist', 30),
  ('akseswa-oto', 'gps', 'GPS', 'GPS', 'GPS', 40),
  ('akseswa-oto', 'chaje-sipo-telefon', 'Chargeurs & supports téléphone', 'Chajè & sipò telefòn', 'Chargers & phone mounts', 50),
  ('akseswa-oto', 'netwayaj-antretyen-oto', 'Nettoyage & entretien auto', 'Netwayaj & antretyen oto', 'Car care & cleaning', 60),
  ('akseswa-oto', 'sekirite', 'Sécurité (extincteurs, triangles, antivols)', 'Sekirite (ekstenktè, triyang)', 'Safety (extinguishers, triangles, locks)', 70),
  ('akseswa-oto', 'bach-pwoteksyon', 'Bâches & protections', 'Bach & pwoteksyon', 'Covers & protection', 80),
  ('ekipman-motosiklis', 'kas', 'Casques', 'Kas', 'Helmets', 10),
  ('ekipman-motosiklis', 'gan-motosiklis', 'Gants', 'Gan motosiklis', 'Gloves', 20),
  ('ekipman-motosiklis', 'ves-pwoteksyon', 'Vestes & protections', 'Vès & pwoteksyon', 'Jackets & protection', 30),
  ('ekipman-motosiklis', 'bot-moto', 'Bottes moto', 'Bòt moto', 'Motorcycle boots', 40),
  ('ekipman-motosiklis', 'antivol-alam', 'Antivols & alarmes', 'Antivòl & alam', 'Locks & alarms', 50),
  ('ekipman-motosiklis', 'top-case-sakoch', 'Top-cases & sacoches', 'Top-case & sakòch', 'Top cases & bags', 60),
  ('ekipman-motosiklis', 'padesi', 'Imperméables', 'Padesi', 'Rain gear', 70),
  ('zouti-garaj', 'kle-douy', 'Clés & douilles', 'Kle & douy', 'Wrenches & sockets', 10),
  ('zouti-garaj', 'krik-chandel', 'Crics & chandelles', 'Krik & chandèl', 'Jacks & stands', 20),
  ('zouti-garaj', 'konprese-gonfle', 'Compresseurs & gonfleurs', 'Konpresè & gonflè', 'Compressors & inflators', 30),
  ('zouti-garaj', 'valiz-dyagnostik-obd', 'Valises de diagnostic OBD', 'Valiz dyagnostik OBD', 'OBD diagnostic tools', 40),
  ('zouti-garaj', 'chaje-batri', 'Chargeurs de batterie', 'Chajè batri', 'Battery chargers', 50),
  ('zouti-garaj', 'kab-demaraj', 'Câbles de démarrage', 'Kab demaraj', 'Jumper cables', 60),
  ('zouti-garaj', 'pwodwi-atelye', 'Produits d''atelier', 'Pwodwi atelye', 'Workshop supplies', 70),
  ('veyikil-2-wou', 'moto', 'Motos', 'Moto', 'Motorcycles', 10),
  ('veyikil-2-wou', 'skoute', 'Scooters', 'Skoutè', 'Scooters', 20),
  ('veyikil-2-wou', 'bisiklet', 'Vélos', 'Bisiklèt', 'Bicycles', 30),
  ('veyikil-2-wou', 'bisiklet-elektrik', 'Vélos électriques', 'Bisiklèt elektrik', 'E-bikes', 40),
  ('veyikil-2-wou', 'pyes-akseswa-bisiklet', 'Pièces & accessoires vélo', 'Pyès & akseswa bisiklèt', 'Bike parts & accessories', 50),
  ('telefon-tablet', 'smartphone', 'Smartphones', 'Smartphone', 'Smartphones', 10),
  ('telefon-tablet', 'telefon-senp', 'Téléphones simples', 'Telefòn senp', 'Basic phones', 20),
  ('telefon-tablet', 'tablet', 'Tablettes', 'Tablèt', 'Tablets', 30),
  ('telefon-tablet', 'mont-konekte', 'Montres connectées', 'Mont konekte', 'Smartwatches', 40),
  ('telefon-tablet', 'pyes-telefon', 'Pièces détachées téléphone (écrans, batteries, connecteurs)', 'Pyès telefòn (ekran, batri)', 'Phone parts (screens, batteries)', 50),
  ('akseswa-telefon', 'kes-etwi', 'Coques & étuis', 'Kès & etwi', 'Cases & covers', 10),
  ('akseswa-telefon', 'pwoteksyon-ekran', 'Protections d''écran', 'Pwoteksyon ekran', 'Screen protectors', 20),
  ('akseswa-telefon', 'chaje-adapte', 'Chargeurs & adaptateurs', 'Chajè & adaptè', 'Chargers & adapters', 30),
  ('akseswa-telefon', 'kab-telefon', 'Câbles', 'Kab telefòn', 'Cables', 40),
  ('akseswa-telefon', 'powerbank', 'Batteries externes (powerbanks)', 'Powerbank', 'Power banks', 50),
  ('akseswa-telefon', 'ekoute-zorey', 'Écouteurs & oreillettes', 'Ekoutè & zòrèy', 'Earphones & headsets', 60),
  ('akseswa-telefon', 'kat-memwa', 'Cartes mémoire', 'Kat memwa', 'Memory cards', 70),
  ('akseswa-telefon', 'sipo-trepye', 'Supports & trépieds', 'Sipò & trepye', 'Mounts & tripods', 80),
  ('enfomatik', 'laptop', 'Ordinateurs portables', 'Laptòp', 'Laptops', 10),
  ('enfomatik', 'odinate-biwo', 'Ordinateurs de bureau', 'Òdinatè biwo', 'Desktop computers', 20),
  ('enfomatik', 'ekran', 'Écrans', 'Ekran', 'Monitors', 30),
  ('enfomatik', 'klavye-sourit', 'Claviers & souris', 'Klavye & sourit', 'Keyboards & mice', 40),
  ('enfomatik', 'enprimant', 'Imprimantes', 'Enprimant', 'Printers', 50),
  ('enfomatik', 'katouch-tone', 'Cartouches & toners', 'Katouch & tonè', 'Ink & toner', 60),
  ('enfomatik', 'stokaj', 'Stockage (clés USB, disques durs)', 'Stokaj (kle USB, disk)', 'Storage (USB drives, hard drives)', 70),
  ('enfomatik', 'rezo', 'Réseau (routeurs, répéteurs)', 'Rezo (routè, repetè)', 'Networking (routers, extenders)', 80),
  ('enfomatik', 'konpozan-pyes-pc', 'Composants & pièces PC', 'Konpozan & pyès PC', 'PC components & parts', 90),
  ('odyo-imaj', 'televizyon', 'Téléviseurs', 'Televizyon', 'TVs', 10),
  ('odyo-imaj', 'bafl-sono', 'Enceintes & sonos', 'Bafl & sono', 'Speakers & sound systems', 20),
  ('odyo-imaj', 'kas-odyo', 'Casques audio', 'Kas odyo', 'Headphones', 30),
  ('odyo-imaj', 'ba-son', 'Barres de son', 'Ba son', 'Soundbars', 40),
  ('odyo-imaj', 'pwojekte', 'Projecteurs', 'Pwojektè', 'Projectors', 50),
  ('odyo-imaj', 'mikwo-materyel-dj', 'Micros & matériel DJ', 'Mikwo & materyèl DJ', 'Mics & DJ gear', 60),
  ('odyo-imaj', 'akseswa-tv', 'Accessoires TV (supports, câbles HDMI)', 'Akseswa TV (sipò, kab HDMI)', 'TV accessories', 70),
  ('eneji-kouran', 'panno-sole', 'Panneaux solaires', 'Panno solè', 'Solar panels', 10),
  ('eneji-kouran', 'batri-sole', 'Batteries solaires', 'Batri solè', 'Solar batteries', 20),
  ('eneji-kouran', 'ondile-inverte', 'Onduleurs & inverters', 'Ondilè & invèrtè', 'Inverters', 30),
  ('eneji-kouran', 'regilate-chaj', 'Régulateurs de charge', 'Regilatè chaj', 'Charge controllers', 40),
  ('eneji-kouran', 'delko', 'Groupes électrogènes (delco)', 'Dèlko', 'Generators', 50),
  ('eneji-kouran', 'anpoul-led', 'Ampoules & LED', 'Anpoul & LED', 'Bulbs & LED', 60),
  ('eneji-kouran', 'lanp-rechajab', 'Lampes rechargeables', 'Lanp rechajab', 'Rechargeable lamps', 70),
  ('eneji-kouran', 'ralonj-miltipriz', 'Rallonges & multiprises', 'Ralonj & miltipriz', 'Extension cords & power strips', 80),
  ('eneji-kouran', 'estabilizate-tansyon', 'Stabilisateurs de tension', 'Estabilizatè tansyon', 'Voltage stabilizers', 90),
  ('eneji-kouran', 'kablaj-elektrik', 'Câblage électrique', 'Kablaj elektrik', 'Electrical wiring', 100),
  ('kamera-sekirite', 'kamera-siveyans', 'Caméras de surveillance', 'Kamera siveyans', 'Security cameras', 10),
  ('kamera-sekirite', 'anrejistre', 'Enregistreurs (DVR/NVR)', 'Anrejistrè (DVR/NVR)', 'Recorders (DVR/NVR)', 20),
  ('kamera-sekirite', 'sonet-videyo', 'Sonnettes vidéo', 'Sonèt videyo', 'Video doorbells', 30),
  ('kamera-sekirite', 'alam-detekte', 'Alarmes & détecteurs', 'Alam & detektè', 'Alarms & detectors', 40),
  ('kamera-sekirite', 'aparey-foto', 'Appareils photo', 'Aparèy foto', 'Cameras', 50),
  ('kamera-sekirite', 'dron', 'Drones', 'Dron', 'Drones', 60),
  ('kamera-sekirite', 'akseswa-foto', 'Accessoires photo', 'Akseswa foto', 'Photo accessories', 70),
  ('rad-fanm', 'wob', 'Robes', 'Wòb', 'Dresses', 10),
  ('rad-fanm', 'blouz-chemizye', 'Hauts & chemisiers', 'Blouz & chemizye', 'Tops & blouses', 20),
  ('rad-fanm', 'pantalon-djin-fanm', 'Pantalons & jeans', 'Pantalon & djin fanm', 'Pants & jeans', 30),
  ('rad-fanm', 'jip', 'Jupes', 'Jip', 'Skirts', 40),
  ('rad-fanm', 'ansanm-taye', 'Ensembles & tailleurs', 'Ansanm & tayè', 'Sets & suits', 50),
  ('rad-fanm', 'lenjri', 'Lingerie', 'Lenjri', 'Lingerie', 60),
  ('rad-fanm', 'mayo-beny', 'Maillots de bain', 'Mayo beny', 'Swimwear', 70),
  ('rad-fanm', 'ves-manto-fanm', 'Vestes & manteaux', 'Vès & manto fanm', 'Jackets & coats', 80),
  ('rad-fanm', 'rad-tradisyonel', 'Tenues traditionnelles (karabela)', 'Rad tradisyonèl (karabela)', 'Traditional wear (karabela)', 90),
  ('rad-gason', 'chemiz', 'Chemises', 'Chemiz', 'Shirts', 10),
  ('rad-gason', 'mayo-polo', 'T-shirts & polos', 'Mayo & polo', 'T-shirts & polos', 20),
  ('rad-gason', 'pantalon-djin-gason', 'Pantalons & jeans', 'Pantalon & djin gason', 'Pants & jeans', 30),
  ('rad-gason', 'chot', 'Shorts', 'Chòt', 'Shorts', 40),
  ('rad-gason', 'kostim', 'Costumes', 'Kostim', 'Suits', 50),
  ('rad-gason', 'souvetman-gason', 'Sous-vêtements', 'Souvètman gason', 'Underwear', 60),
  ('rad-gason', 'ves-gason', 'Vestes', 'Vès gason', 'Jackets', 70),
  ('rad-gason', 'rad-tradisyonel-gason', 'Tenues traditionnelles', 'Rad tradisyonèl gason', 'Traditional wear', 80),
  ('rad-timoun', 'bebe-0-2-zan', 'Bébé 0-2 ans', 'Bebe 0-2 zan', 'Baby 0-2 years', 10),
  ('rad-timoun', 'rad-tifi', 'Fille', 'Rad tifi', 'Girls', 20),
  ('rad-timoun', 'rad-tigason', 'Garçon', 'Rad tigason', 'Boys', 30),
  ('rad-timoun', 'inifom-lekol', 'Uniformes scolaires', 'Inifòm lekòl', 'School uniforms', 40),
  ('rad-timoun', 'rad-seremoni', 'Tenues de cérémonie', 'Rad seremoni', 'Formal wear', 50),
  ('bijou-mont', 'kolye', 'Colliers', 'Kolye', 'Necklaces', 10),
  ('bijou-mont', 'brasle', 'Bracelets', 'Braslè', 'Bracelets', 20),
  ('bijou-mont', 'zanno', 'Boucles d''oreilles', 'Zanno', 'Earrings', 30),
  ('bijou-mont', 'bag', 'Bagues', 'Bag', 'Rings', 40),
  ('bijou-mont', 'mont-gason', 'Montres homme', 'Mont gason', 'Men''s watches', 50),
  ('bijou-mont', 'mont-fanm', 'Montres femme', 'Mont fanm', 'Women''s watches', 60),
  ('bijou-mont', 'pariur', 'Parures', 'Pariur', 'Jewelry sets', 70),
  ('bijou-mont', 'bijou-atizanal', 'Bijoux artisanaux', 'Bijou atizanal', 'Handmade jewelry', 80),
  ('akseswa-mod', 'senti', 'Ceintures', 'Senti', 'Belts', 10),
  ('akseswa-mod', 'chapo-kasket', 'Chapeaux & casquettes', 'Chapo & kaskèt', 'Hats & caps', 20),
  ('akseswa-mod', 'linet-soley', 'Lunettes de soleil', 'Linèt solèy', 'Sunglasses', 30),
  ('akseswa-mod', 'foula-echap', 'Foulards & écharpes', 'Foula & echap', 'Scarves', 40),
  ('akseswa-mod', 'bous-potfey', 'Portefeuilles', 'Bous & pòtfèy', 'Wallets', 50),
  ('akseswa-mod', 'gan', 'Gants', 'Gan', 'Gloves', 60),
  ('akseswa-mod', 'kravat-ne-papiyon', 'Cravates & nœuds papillon', 'Kravat & ne papiyon', 'Ties & bow ties', 70),
  ('soulye-fanm', 'sandal-fanm', 'Sandales', 'Sandal fanm', 'Sandals', 10),
  ('soulye-fanm', 'talon', 'Talons', 'Talon', 'Heels', 20),
  ('soulye-fanm', 'basket-fanm', 'Baskets', 'Baskèt fanm', 'Sneakers', 30),
  ('soulye-fanm', 'balerin', 'Ballerines', 'Balerin', 'Flats', 40),
  ('soulye-fanm', 'bot-fanm', 'Bottes', 'Bòt fanm', 'Boots', 50),
  ('soulye-fanm', 'mil-klaket', 'Mules & claquettes', 'Mil & klakèt', 'Mules & slides', 60),
  ('soulye-gason', 'basket-gason', 'Baskets', 'Baskèt gason', 'Sneakers', 10),
  ('soulye-gason', 'soulye-vil', 'Chaussures de ville', 'Soulye vil', 'Dress shoes', 20),
  ('soulye-gason', 'mokasen', 'Mocassins', 'Mokasen', 'Loafers', 30),
  ('soulye-gason', 'sandal-gason', 'Sandales', 'Sandal gason', 'Sandals', 40),
  ('soulye-gason', 'bot-gason', 'Bottes', 'Bòt gason', 'Boots', 50),
  ('soulye-gason', 'tong', 'Tongs', 'Tong', 'Flip-flops', 60),
  ('soulye-timoun', 'soulye-bebe', 'Bébé', 'Soulye bebe', 'Baby shoes', 10),
  ('soulye-timoun', 'soulye-tifi', 'Fille', 'Soulye tifi', 'Girls'' shoes', 20),
  ('soulye-timoun', 'soulye-tigason', 'Garçon', 'Soulye tigason', 'Boys'' shoes', 30),
  ('soulye-timoun', 'soulye-lekol', 'Chaussures scolaires', 'Soulye lekòl', 'School shoes', 40),
  ('soulye-timoun', 'basket-timoun', 'Baskets enfant', 'Baskèt timoun', 'Kids'' sneakers', 50),
  ('antretyen-soulye', 'siraj-antretyen', 'Cirage & entretien', 'Siraj & antretyen', 'Polish & care', 10),
  ('antretyen-soulye', 'semel', 'Semelles', 'Semèl', 'Insoles', 20),
  ('antretyen-soulye', 'laset', 'Lacets', 'Lasèt', 'Laces', 30),
  ('antretyen-soulye', 'anbochwa', 'Embauchoirs', 'Anbochwa', 'Shoe trees', 40),
  ('sak-fanm', 'sak-men', 'Sacs à main', 'Sak men', 'Handbags', 10),
  ('sak-fanm', 'sak-bandoulye', 'Sacs bandoulière', 'Sak bandoulyè', 'Crossbody bags', 20),
  ('sak-fanm', 'pochet', 'Pochettes', 'Pochèt', 'Clutches', 30),
  ('sak-fanm', 'sak-do-fanm', 'Sacs à dos femme', 'Sak do fanm', 'Women''s backpacks', 40),
  ('sak-fanm', 'kaba', 'Cabas', 'Kaba', 'Totes', 50),
  ('sak-vwayaj', 'valiz', 'Valises', 'Valiz', 'Suitcases', 10),
  ('sak-vwayaj', 'sak-vwayaj', 'Sacs de voyage', 'Sak vwayaj', 'Travel bags', 20),
  ('sak-vwayaj', 'sak-kabin', 'Sacs de cabine', 'Sak kabin', 'Cabin bags', 30),
  ('sak-vwayaj', 'fouwo-akseswa-valiz', 'Housses & accessoires', 'Fouwo & akseswa valiz', 'Luggage covers & accessories', 40),
  ('sak-lekol', 'sak-do-lekol', 'Sacs à dos scolaires', 'Sak do lekòl', 'School backpacks', 10),
  ('sak-lekol', 'katab', 'Cartables', 'Katab', 'Satchels', 20),
  ('sak-lekol', 'sak-a-woulet', 'Sacs à roulettes', 'Sak a woulèt', 'Rolling bags', 30),
  ('sak-lekol', 'twous', 'Trousses', 'Twous', 'Pencil cases', 40),
  ('sak-travay', 'sakoch-odinate', 'Sacoches ordinateur', 'Sakòch òdinatè', 'Laptop bags', 10),
  ('sak-travay', 'sevyet-pot-dokiman', 'Serviettes & porte-documents', 'Sèvyèt & pòt-dokiman', 'Briefcases', 20),
  ('sak-travay', 'sak-zouti', 'Sacs à outils', 'Sak zouti', 'Tool bags', 30),
  ('swen-cheve', 'chanpou', 'Shampoings', 'Chanpou', 'Shampoos', 10),
  ('swen-cheve', 'apre-chanpou-mask', 'Après-shampoings & masques', 'Apre-chanpou & mask', 'Conditioners & masks', 20),
  ('swen-cheve', 'luil-sewom-cheve', 'Huiles & sérums capillaires', 'Luil & sewòm cheve', 'Hair oils & serums', 30),
  ('swen-cheve', 'mech-ekstansyon', 'Mèches & extensions', 'Mèch & ekstansyon', 'Weaves & extensions', 40),
  ('swen-cheve', 'perik', 'Perruques', 'Perik', 'Wigs', 50),
  ('swen-cheve', 'tres-kwoche', 'Tresses & crochets', 'Très & kwochè', 'Braids & crochet hair', 60),
  ('swen-cheve', 'defrizan-teksturizan', 'Défrisants & texturisants', 'Defrizan & teksturizan', 'Relaxers & texturizers', 70),
  ('swen-cheve', 'jel-fiksate', 'Gels & fixateurs', 'Jèl & fiksatè', 'Gels & holding products', 80),
  ('swen-cheve', 'akseswa-kwafi', 'Accessoires coiffure (peignes, brosses, pinces)', 'Akseswa kwafi (peny, bwòs)', 'Hair tools (combs, brushes, clips)', 90),
  ('swen-cheve', 'pwodwi-cheve-natirel', 'Produits cheveux naturels/crépus', 'Pwodwi cheve natirèl', 'Natural hair products', 100),
  ('swen-po', 'krem-figi', 'Crèmes visage', 'Krèm figi', 'Face creams', 10),
  ('swen-po', 'let-krem-ko', 'Laits & crèmes corps', 'Lèt & krèm kò', 'Body lotions & creams', 20),
  ('swen-po', 'sewom', 'Sérums', 'Sewòm', 'Serums', 30),
  ('swen-po', 'netwayan-tonik', 'Nettoyants & toniques', 'Netwayan & tonik', 'Cleansers & toners', 40),
  ('swen-po', 'pwoteksyon-sole', 'Protections solaires', 'Pwoteksyon solè', 'Sunscreen', 50),
  ('swen-po', 'savon-swen', 'Savons de soin', 'Savon swen', 'Care soaps', 60),
  ('swen-po', 'swen-sible', 'Soins ciblés (taches, acné)', 'Swen sible (tach, akne)', 'Targeted care (spots, acne)', 70),
  ('swen-po', 'be-luil-natirel', 'Beurres & huiles naturelles (karité, coco, ricin)', 'Bè & luil natirèl (karite, kokoye)', 'Natural butters & oils (shea, coconut, castor)', 80),
  ('makiyaj', 'fon-tent-poud', 'Fond de teint & poudres', 'Fon tent & poud', 'Foundation & powders', 10),
  ('makiyaj', 'je', 'Yeux (mascara, fards, crayons)', 'Je (maskara, fa, kreyon)', 'Eyes (mascara, shadow, liners)', 20),
  ('makiyaj', 'bouch', 'Lèvres (rouges, gloss)', 'Bouch (fa bouch, gloss)', 'Lips (lipstick, gloss)', 30),
  ('makiyaj', 'zong', 'Ongles (vernis, faux ongles, soins)', 'Zong (vèni, fo zong)', 'Nails (polish, false nails, care)', 40),
  ('makiyaj', 'penso-eponj', 'Pinceaux & éponges', 'Penso & eponj', 'Brushes & sponges', 50),
  ('makiyaj', 'palet-makiyaj', 'Palettes', 'Palèt makiyaj', 'Palettes', 60),
  ('pafen', 'pafen-fanm', 'Parfums femme', 'Pafen fanm', 'Women''s fragrances', 10),
  ('pafen', 'pafen-gason', 'Parfums homme', 'Pafen gason', 'Men''s fragrances', 20),
  ('pafen', 'deyodoran', 'Déodorants', 'Deyodoran', 'Deodorants', 30),
  ('pafen', 'brim-ko', 'Brumes corporelles', 'Brim kò', 'Body mists', 40),
  ('pafen', 'kofre-pafen', 'Coffrets', 'Kofrè pafen', 'Gift sets', 50),
  ('ijyen-pesonel', 'dantifris-bwos-dan', 'Dentifrices & brosses à dents', 'Dantifris & bwòs dan', 'Toothpaste & toothbrushes', 10),
  ('ijyen-pesonel', 'papye-ijyenik', 'Papier hygiénique', 'Papye ijyenik', 'Toilet paper', 20),
  ('ijyen-pesonel', 'sevyet-pwoteksyon-peryodik', 'Serviettes & protections périodiques', 'Sèvyèt & pwoteksyon peryodik', 'Pads & period care', 30),
  ('ijyen-pesonel', 'razaj-epilasyon', 'Rasage & épilation', 'Razaj & epilasyon', 'Shaving & hair removal', 40),
  ('ijyen-pesonel', 'savon-jel-douch', 'Savons & gels douche', 'Savon & jèl douch', 'Soaps & shower gels', 50),
  ('ijyen-pesonel', 'koton-lenget', 'Cotons & lingettes', 'Koton & lengèt', 'Cotton & wipes', 60),
  ('apare-bote', 'sechwa-cheve', 'Sèche-cheveux', 'Sechwa cheve', 'Hair dryers', 10),
  ('apare-bote', 'tondez-razwa-elektrik', 'Tondeuses & rasoirs électriques', 'Tondèz & razwa elektrik', 'Clippers & electric shavers', 20),
  ('apare-bote', 'fe-plat-boukle', 'Fers à lisser & à boucler', 'Fè plat & boukle', 'Straighteners & curlers', 30),
  ('apare-bote', 'epilate', 'Épilateurs', 'Epilatè', 'Epilators', 40),
  ('apare-bote', 'aparey-swen-figi', 'Appareils de soin visage', 'Aparèy swen figi', 'Facial care devices', 50),
  ('apare-bote', 'miwa-limine', 'Miroirs lumineux', 'Miwa limine', 'Lighted mirrors', 60),
  ('savon', 'savon-twalet', 'Savon de toilette', 'Savon twalèt', 'Bath soap', 10),
  ('savon', 'savon-atizanal', 'Savon artisanal', 'Savon atizanal', 'Handmade soap', 20),
  ('savon', 'savon-nwa', 'Savon noir', 'Savon nwa', 'Black soap', 30),
  ('savon', 'savon-likid', 'Savon liquide', 'Savon likid', 'Liquid soap', 40),
  ('savon', 'savon-marsey', 'Savon de Marseille', 'Savon Marsèy', 'Marseille soap', 50),
  ('savon', 'savon-antiseptik', 'Savon antiseptique', 'Savon antiseptik', 'Antiseptic soap', 60),
  ('lesiv', 'lesiv-an-poud', 'Lessive en poudre', 'Lesiv an poud', 'Powder detergent', 10),
  ('lesiv', 'lesiv-likid', 'Lessive liquide', 'Lesiv likid', 'Liquid detergent', 20),
  ('lesiv', 'adousisan', 'Adoucissants', 'Adousisan', 'Fabric softeners', 30),
  ('lesiv', 'klowoks', 'Eau de Javel', 'Klowòks', 'Bleach', 40),
  ('lesiv', 'detachan', 'Détachants', 'Detachan', 'Stain removers', 50),
  ('lesiv', 'lanmidon', 'Amidon', 'Lanmidon', 'Starch', 60),
  ('netwayaj-kay', 'netwayan-ate-sifas', 'Nettoyants sols & surfaces', 'Netwayan atè & sifas', 'Floor & surface cleaners', 10),
  ('netwayaj-kay', 'likid-vesel', 'Liquide vaisselle', 'Likid vesèl', 'Dish soap', 20),
  ('netwayaj-kay', 'dezenfektan', 'Désinfectants', 'Dezenfektan', 'Disinfectants', 30),
  ('netwayaj-kay', 'ensektisid-repousan', 'Insecticides & répulsifs', 'Ensektisid & repousan', 'Insecticides & repellents', 40),
  ('netwayaj-kay', 'dezodorizan', 'Désodorisants', 'Dezodorizan', 'Air fresheners', 50),
  ('netwayaj-kay', 'netwayan-sanite', 'Nettoyants sanitaires', 'Netwayan sanitè', 'Bathroom cleaners', 60),
  ('materyel-netwayaj', 'bale-mop', 'Balais & serpillières', 'Bale & mòp', 'Brooms & mops', 10),
  ('materyel-netwayaj', 'bokit-basin', 'Seaux & bassines', 'Bokit & basin', 'Buckets & basins', 20),
  ('materyel-netwayaj', 'eponj-chifon', 'Éponges & chiffons', 'Eponj & chifon', 'Sponges & cloths', 30),
  ('materyel-netwayaj', 'gan-menaj', 'Gants de ménage', 'Gan menaj', 'Cleaning gloves', 40),
  ('materyel-netwayaj', 'poubel-sak-fatra', 'Poubelles & sacs', 'Poubèl & sak fatra', 'Trash cans & bags', 50),
  ('pwodwi-sek', 'diri', 'Riz', 'Diri', 'Rice', 10),
  ('pwodwi-sek', 'pwa', 'Haricots (pwa)', 'Pwa', 'Beans', 20),
  ('pwodwi-sek', 'mayi-farin', 'Maïs & farines', 'Mayi & farin', 'Corn & flours', 30),
  ('pwodwi-sek', 'pat-alimante', 'Pâtes', 'Pat alimantè', 'Pasta', 40),
  ('pwodwi-sek', 'luil-kwizin', 'Huiles de cuisine', 'Luil kwizin', 'Cooking oils', 50),
  ('pwodwi-sek', 'sik-sel', 'Sucre & sel', 'Sik & sèl', 'Sugar & salt', 60),
  ('pwodwi-sek', 'epis-asezonman', 'Épices & assaisonnements', 'Epis & asezonman', 'Spices & seasonings', 70),
  ('pwodwi-sek', 'let-an-poud', 'Lait en poudre', 'Lèt an poud', 'Powdered milk', 80),
  ('bwason', 'dlo', 'Eau', 'Dlo', 'Water', 10),
  ('bwason', 'ji', 'Jus', 'Ji', 'Juices', 20),
  ('bwason', 'soda', 'Sodas', 'Soda', 'Sodas', 30),
  ('bwason', 'kafe', 'Café', 'Kafe', 'Coffee', 40),
  ('bwason', 'te-tizann', 'Thé & tisanes', 'Te & tizann', 'Tea & infusions', 50),
  ('bwason', 'bwason-enejizan', 'Boissons énergisantes', 'Bwason enèjizan', 'Energy drinks', 60),
  ('bwason', 'siwo', 'Sirops', 'Siwo', 'Syrups', 70),
  ('pwodwi-lokal', 'rapadou', 'Rapadou', 'Rapadou', 'Rapadou', 10),
  ('pwodwi-lokal', 'manba', 'Mamba (beurre d''arachide)', 'Manba', 'Mamba (peanut butter)', 20),
  ('pwodwi-lokal', 'kasav', 'Cassave', 'Kasav', 'Cassava bread', 30),
  ('pwodwi-lokal', 'kafe-ayisyen', 'Café haïtien', 'Kafe ayisyen', 'Haitian coffee', 40),
  ('pwodwi-lokal', 'kakawo', 'Cacao', 'Kakawo', 'Cocoa', 50),
  ('pwodwi-lokal', 'epis-kreyol', 'Épices créoles (epis)', 'Epis kreyòl', 'Creole spice blends (epis)', 60),
  ('pwodwi-lokal', 'konfiti-lokal', 'Confitures locales', 'Konfiti lokal', 'Local jams', 70),
  ('pwodwi-lokal', 'siwo-myel-lokal', 'Miel local', 'Siwo myèl lokal', 'Local honey', 80),
  ('konsev-sos', 'konsev', 'Conserves', 'Konsèv', 'Canned goods', 10),
  ('konsev-sos', 'sos-piman', 'Sauces & piments', 'Sòs & piman', 'Sauces & hot peppers', 20),
  ('konsev-sos', 'vineg', 'Vinaigres', 'Vinèg', 'Vinegars', 30),
  ('konsev-sos', 'mayonez-moutad', 'Mayonnaise & moutarde', 'Mayonèz & moutad', 'Mayonnaise & mustard', 40),
  ('konsev-sos', 'bouyon-kib', 'Bouillons', 'Bouyon kib', 'Bouillon', 50),
  ('goute-bonbon', 'biswit', 'Biscuits', 'Biswit', 'Biscuits', 10),
  ('goute-bonbon', 'chips-goute-sale', 'Chips & snacks salés', 'Chips & goute sale', 'Chips & salty snacks', 20),
  ('goute-bonbon', 'bonbon', 'Bonbons', 'Bonbon', 'Candy', 30),
  ('goute-bonbon', 'chokola', 'Chocolats', 'Chokola', 'Chocolate', 40),
  ('goute-bonbon', 'fwi-sek', 'Fruits secs', 'Fwi sèk', 'Dried fruits & nuts', 50),
  ('legim-fwi', 'legim-fre', 'Légumes frais', 'Legim fre', 'Fresh vegetables', 10),
  ('legim-fwi', 'fwi-fre', 'Fruits frais', 'Fwi fre', 'Fresh fruits', 20),
  ('legim-fwi', 'vive', 'Tubercules (igname, patate, manioc)', 'Vivè (yanm, patat, manyòk)', 'Tubers (yam, sweet potato, cassava)', 30),
  ('legim-fwi', 'fig-bannann', 'Bananes & plantains', 'Fig & bannann', 'Bananas & plantains', 40),
  ('legim-fwi', 'fey-santi-bon', 'Herbes aromatiques', 'Fèy santi bon', 'Fresh herbs', 50),
  ('grenn-semans', 'semans-jaden', 'Semences potagères', 'Semans jaden', 'Vegetable seeds', 10),
  ('grenn-semans', 'semans-manje', 'Semences vivrières', 'Semans manje', 'Food crop seeds', 20),
  ('grenn-semans', 'plant-bouti', 'Plants & boutures', 'Plant & bouti', 'Seedlings & cuttings', 30),
  ('grenn-semans', 'te-terite', 'Terreau', 'Tè & teritè', 'Potting soil', 40),
  ('zouti-agrikol', 'manchet', 'Machettes (manchèt)', 'Manchèt', 'Machetes', 10),
  ('zouti-agrikol', 'wou-pikwa', 'Houes & pioches', 'Wou & pikwa', 'Hoes & pickaxes', 20),
  ('zouti-agrikol', 'awozwa', 'Arrosoirs', 'Awozwa', 'Watering cans', 30),
  ('zouti-agrikol', 'pilverizate', 'Pulvérisateurs', 'Pilverizatè', 'Sprayers', 40),
  ('zouti-agrikol', 'sekate', 'Sécateurs', 'Sekatè', 'Pruners', 50),
  ('zouti-agrikol', 'bouret', 'Brouettes', 'Bourèt', 'Wheelbarrows', 60),
  ('angre-tretman', 'angre-oganik', 'Engrais organiques', 'Angrè òganik', 'Organic fertilizers', 10),
  ('angre-tretman', 'angre-chimik', 'Engrais chimiques', 'Angrè chimik', 'Chemical fertilizers', 20),
  ('angre-tretman', 'pestisid', 'Pesticides', 'Pestisid', 'Pesticides', 30),
  ('angre-tretman', 'fonjisid', 'Fongicides', 'Fonjisid', 'Fungicides', 40),
  ('bet-pwovann', 'volay', 'Volailles', 'Volay', 'Poultry', 10),
  ('bet-pwovann', 'ti-bet', 'Petit bétail', 'Ti bèt', 'Small livestock', 20),
  ('bet-pwovann', 'manje-volay', 'Aliments pour volaille', 'Manje volay', 'Poultry feed', 30),
  ('bet-pwovann', 'manje-bet', 'Aliments pour bétail', 'Manje bèt', 'Livestock feed', 40),
  ('bet-pwovann', 'materyel-elvaj', 'Matériel d''élevage (abreuvoirs, mangeoires)', 'Materyèl elvaj', 'Livestock equipment', 50),
  ('bet-pwovann', 'pwodwi-veterine', 'Produits vétérinaires', 'Pwodwi veterinè', 'Veterinary products', 60),
  ('meb', 'salon', 'Salon', 'Salon', 'Living room', 10),
  ('meb', 'chanm', 'Chambre', 'Chanm', 'Bedroom', 20),
  ('meb', 'sal-a-manje', 'Salle à manger', 'Sal a manje', 'Dining room', 30),
  ('meb', 'biwo', 'Bureau', 'Biwo', 'Office', 40),
  ('meb', 'ranjman-amwa', 'Rangement & armoires', 'Ranjman & amwa', 'Storage & wardrobes', 50),
  ('meb', 'meb-deyo', 'Mobilier extérieur', 'Mèb deyò', 'Outdoor furniture', 60),
  ('meb', 'meb-timoun', 'Meubles enfants', 'Mèb timoun', 'Kids'' furniture', 70),
  ('kizin', 'kastwol-mamit', 'Casseroles & marmites', 'Kastwòl & mamit', 'Pots & pans', 10),
  ('kizin', 'pwelon', 'Poêles', 'Pwelon', 'Frying pans', 20),
  ('kizin', 'istansil', 'Ustensiles', 'Istansil', 'Utensils', 30),
  ('kizin', 'vesel', 'Vaisselle', 'Vesèl', 'Dishware', 40),
  ('kizin', 've-tas', 'Verres & tasses', 'Vè & tas', 'Glasses & cups', 50),
  ('kizin', 'kouve', 'Couverts', 'Kouvè', 'Cutlery', 60),
  ('kizin', 'konsevasyon-bwat', 'Conservation & boîtes', 'Konsèvasyon & bwat', 'Food storage', 70),
  ('kizin', 'chodye-tradisyonel', 'Chaudières traditionnelles', 'Chodyè tradisyonèl', 'Traditional cookware', 80),
  ('elektwomenaje', 'frijide', 'Réfrigérateurs', 'Frijidè', 'Refrigerators', 10),
  ('elektwomenaje', 'konjelate', 'Congélateurs', 'Konjelatè', 'Freezers', 20),
  ('elektwomenaje', 'kwizinye-recho', 'Cuisinières & réchauds', 'Kwizinyè & recho', 'Stoves & burners', 30),
  ('elektwomenaje', 'mikwo-ond', 'Micro-ondes', 'Mikwo-ond', 'Microwaves', 40),
  ('elektwomenaje', 'mikse-blende', 'Mixeurs & blenders', 'Miksè & blendè', 'Mixers & blenders', 50),
  ('elektwomenaje', 'machin-lave-rad', 'Machines à laver', 'Machin lave rad', 'Washing machines', 60),
  ('elektwomenaje', 'vantilate', 'Ventilateurs', 'Vantilatè', 'Fans', 70),
  ('elektwomenaje', 'klimatize', 'Climatiseurs', 'Klimatizè', 'Air conditioners', 80),
  ('elektwomenaje', 'fe-repase', 'Fers à repasser', 'Fè repase', 'Irons', 90),
  ('elektwomenaje', 'bouywa', 'Bouilloires', 'Bouywa', 'Kettles', 100),
  ('dekorasyon', 'rido', 'Rideaux', 'Rido', 'Curtains', 10),
  ('dekorasyon', 'tapi-kay', 'Tapis', 'Tapi kay', 'Rugs', 20),
  ('dekorasyon', 'limine', 'Luminaires', 'Liminè', 'Lighting', 30),
  ('dekorasyon', 'kad-miwa', 'Cadres & miroirs', 'Kad & miwa', 'Frames & mirrors', 40),
  ('dekorasyon', 'plant-po-fle', 'Plantes & pots', 'Plant & po flè', 'Plants & pots', 50),
  ('dekorasyon', 'obje-dekoratif', 'Objets décoratifs', 'Objè dekoratif', 'Decorative objects', 60),
  ('dekorasyon', 'oloj', 'Horloges', 'Òlòj', 'Clocks', 70),
  ('kabann-twal', 'matla', 'Matelas', 'Matla', 'Mattresses', 10),
  ('kabann-twal', 'dra-pari', 'Draps & parures', 'Dra & pari', 'Sheets & bedding sets', 20),
  ('kabann-twal', 'zorye', 'Oreillers', 'Zòrye', 'Pillows', 30),
  ('kabann-twal', 'kouveti', 'Couvertures', 'Kouvèti', 'Blankets', 40),
  ('kabann-twal', 'moustike', 'Moustiquaires', 'Moustikè', 'Mosquito nets', 50),
  ('kabann-twal', 'sevyet-beny', 'Serviettes de bain', 'Sèvyèt beny', 'Bath towels', 60),
  ('kabann-twal', 'nap-tab', 'Nappes', 'Nap tab', 'Tablecloths', 70),
  ('konstriksyon', 'zouti-a-men', 'Outils à main', 'Zouti a men', 'Hand tools', 10),
  ('konstriksyon', 'zouti-elektrik', 'Outillage électroportatif', 'Zouti elektrik', 'Power tools', 20),
  ('konstriksyon', 'penti-penso', 'Peinture & pinceaux', 'Penti & penso', 'Paint & brushes', 30),
  ('konstriksyon', 'plonbri', 'Plomberie', 'Plonbri', 'Plumbing', 40),
  ('konstriksyon', 'elektrisite-kab', 'Électricité & câbles', 'Elektrisite & kab', 'Electrical & cables', 50),
  ('konstriksyon', 'kenkayri', 'Quincaillerie (vis, clous)', 'Kenkayri (vis, klou)', 'Hardware (screws, nails)', 60),
  ('konstriksyon', 'materyo', 'Matériaux (ciment, carrelage)', 'Materyo (siman, karo)', 'Materials (cement, tiles)', 70),
  ('konstriksyon', 'echel', 'Échelles', 'Echèl', 'Ladders', 80),
  ('konstriksyon', 'seriri', 'Serrurerie', 'Seriri', 'Locks & security hardware', 90),
  ('parafamasi', 'vitamin-konpleman', 'Vitamines & compléments', 'Vitamin & konpleman', 'Vitamins & supplements', 10),
  ('parafamasi', 'premye-swen', 'Premiers soins', 'Premye swen', 'First aid', 20),
  ('parafamasi', 'temomet', 'Thermomètres', 'Tèmomèt', 'Thermometers', 30),
  ('parafamasi', 'tansyomet', 'Tensiomètres', 'Tansyomèt', 'Blood pressure monitors', 40),
  ('parafamasi', 'glikomet', 'Glucomètres', 'Glikomèt', 'Glucose meters', 50),
  ('parafamasi', 'antiseptik', 'Antiseptiques', 'Antiseptik', 'Antiseptics', 60),
  ('pwodwi-natirel', 'tizann-fey', 'Tisanes & feuilles', 'Tizann & fèy', 'Herbal teas & leaves', 10),
  ('pwodwi-natirel', 'luil-esansyel', 'Huiles essentielles', 'Luil esansyèl', 'Essential oils', 20),
  ('pwodwi-natirel', 'remed-tradisyonel', 'Remèdes traditionnels', 'Remèd tradisyonèl', 'Traditional remedies', 30),
  ('pwodwi-natirel', 'konpleman-natirel', 'Compléments naturels', 'Konpleman natirèl', 'Natural supplements', 40),
  ('materyel-medikal', 'mask-gan-medikal', 'Masques & gants', 'Mask & gan medikal', 'Masks & gloves', 10),
  ('materyel-medikal', 'beki-deanbilate', 'Béquilles & déambulateurs', 'Beki & deanbilatè', 'Crutches & walkers', 20),
  ('materyel-medikal', 'fotey-woulan', 'Fauteuils roulants', 'Fotèy woulan', 'Wheelchairs', 30),
  ('materyel-medikal', 'pansman-bandaj', 'Pansements & bandages', 'Pansman & bandaj', 'Dressings & bandages', 40),
  ('materyel-medikal', 'materyel-dyagnostik', 'Matériel de diagnostic', 'Materyèl dyagnostik', 'Diagnostic equipment', 50),
  ('ekipman-espo', 'foutbol', 'Football', 'Foutbòl', 'Soccer', 10),
  ('ekipman-espo', 'basketbol', 'Basketball', 'Baskètbòl', 'Basketball', 20),
  ('ekipman-espo', 'fitness-miskilasyon', 'Fitness & musculation', 'Fitness & miskilasyon', 'Fitness & weights', 30),
  ('ekipman-espo', 'atizay-masyal', 'Arts martiaux', 'Atizay masyal', 'Martial arts', 40),
  ('ekipman-espo', 'natasyon', 'Natation', 'Natasyon', 'Swimming', 50),
  ('ekipman-espo', 'tenis-raket', 'Tennis & raquettes', 'Tenis & rakèt', 'Tennis & rackets', 60),
  ('ekipman-espo', 'balon', 'Ballons', 'Balon', 'Balls', 70),
  ('rad-espo', 'mayo-chot-espo', 'Maillots & shorts', 'Mayo & chòt espò', 'Jerseys & shorts', 10),
  ('rad-espo', 'soulye-espo', 'Chaussures de sport', 'Soulye espò', 'Athletic shoes', 20),
  ('rad-espo', 'sivetman', 'Survêtements', 'Sivètman', 'Tracksuits', 30),
  ('rad-espo', 'akseswa-espo', 'Accessoires (gants, protections)', 'Akseswa espò (gan, pwoteksyon)', 'Accessories (gloves, protection)', 40),
  ('aktivite-deyo', 'kanpin', 'Camping', 'Kanpin', 'Camping', 10),
  ('aktivite-deyo', 'lapech', 'Pêche', 'Lapèch', 'Fishing', 20),
  ('aktivite-deyo', 'plaj', 'Plage', 'Plaj', 'Beach', 30),
  ('aktivite-deyo', 'randone', 'Randonnée', 'Randone', 'Hiking', 40),
  ('aktivite-deyo', 'goud-glasye', 'Gourdes & glacières', 'Goud & glasyè', 'Bottles & coolers', 50),
  ('jwet-lwazi', 'jwet-sosyete', 'Jeux de société', 'Jwèt sosyete', 'Board games', 10),
  ('jwet-lwazi', 'domino-kat', 'Dominos & cartes', 'Domino & kat', 'Dominoes & cards', 20),
  ('jwet-lwazi', 'puzzle', 'Puzzles', 'Puzzle', 'Puzzles', 30),
  ('jwet-lwazi', 'jwet-videyo-konsol', 'Jeux vidéo & consoles', 'Jwèt videyo & konsòl', 'Video games & consoles', 40),
  ('liv', 'manyel-lekol', 'Manuels scolaires', 'Manyèl lekòl', 'Textbooks', 10),
  ('liv', 'woman', 'Romans', 'Woman', 'Novels', 20),
  ('liv', 'liv-relijye', 'Livres religieux', 'Liv relijye', 'Religious books', 30),
  ('liv', 'liv-jenes', 'Jeunesse', 'Liv jenès', 'Children''s books', 40),
  ('liv', 'liv-pwofesyonel-teknik', 'Professionnels & techniques', 'Liv pwofesyonèl & teknik', 'Professional & technical', 50),
  ('liv', 'liv-an-kreyol', 'Livres en créole', 'Liv an kreyòl', 'Books in Creole', 60),
  ('liv', 'diksyone', 'Dictionnaires', 'Diksyonè', 'Dictionaries', 70),
  ('founiti-lekol', 'kaye', 'Cahiers', 'Kaye', 'Notebooks', 10),
  ('founiti-lekol', 'plim-kreyon', 'Stylos & crayons', 'Plim & kreyon', 'Pens & pencils', 20),
  ('founiti-lekol', 'kalkilatris', 'Calculatrices', 'Kalkilatris', 'Calculators', 30),
  ('founiti-lekol', 'reg-jewometri', 'Règles & géométrie', 'Règ & jewometri', 'Rulers & geometry sets', 40),
  ('founiti-lekol', 'sak-twous-lekol', 'Sacs & trousses', 'Sak & twous lekòl', 'Bags & pencil cases', 50),
  ('founiti-lekol', 'inifom', 'Uniformes', 'Inifòm', 'Uniforms', 60),
  ('founiti-biwo', 'klase-chemiz-dosye', 'Classeurs & chemises', 'Klasè & chemiz dosye', 'Binders & folders', 10),
  ('founiti-biwo', 'papye-ramet', 'Papier & ramettes', 'Papye & ramèt', 'Paper & reams', 20),
  ('founiti-biwo', 'lank-tone-biwo', 'Encre & toners', 'Lank & tonè biwo', 'Ink & toners', 30),
  ('founiti-biwo', 'ajanda', 'Agendas', 'Ajanda', 'Planners', 40),
  ('founiti-biwo', 'tanpon', 'Tampons', 'Tanpon', 'Stamps', 50),
  ('founiti-biwo', 'ti-materyel-biwo', 'Petit matériel', 'Ti materyèl biwo', 'Office supplies', 60),
  ('atizay-kreyasyon', 'penti-twal-atizay', 'Peinture & toiles', 'Penti & twal atizay', 'Paint & canvases', 10),
  ('atizay-kreyasyon', 'desen', 'Dessin', 'Desen', 'Drawing', 20),
  ('atizay-kreyasyon', 'lwazi-kreyatif', 'Loisirs créatifs', 'Lwazi kreyatif', 'Crafts', 30),
  ('atizay-kreyasyon', 'materyel-kouti', 'Matériel de couture', 'Materyèl kouti', 'Sewing supplies', 40),
  ('swen-bebe', 'kouchet', 'Couches (kouchèt)', 'Kouchèt', 'Diapers', 10),
  ('swen-bebe', 'lenget-bebe', 'Lingettes', 'Lengèt bebe', 'Baby wipes', 20),
  ('swen-bebe', 'krem-swen-bebe', 'Crèmes & soins', 'Krèm & swen bebe', 'Baby creams & care', 30),
  ('swen-bebe', 'bibon-tetin', 'Biberons & tétines', 'Bibon & tetin', 'Bottles & pacifiers', 40),
  ('swen-bebe', 'let-bebe', 'Lait infantile', 'Lèt bebe', 'Infant formula', 50),
  ('swen-bebe', 'bavet', 'Bavoirs', 'Bavèt', 'Bibs', 60),
  ('swen-bebe', 'beny-bebe', 'Bain bébé', 'Beny bebe', 'Baby bath', 70),
  ('materyel-bebe', 'pouset', 'Poussettes', 'Pousèt', 'Strollers', 10),
  ('materyel-bebe', 'syej-oto-bebe', 'Sièges auto', 'Syèj oto bebe', 'Car seats', 20),
  ('materyel-bebe', 'kabann-beso', 'Lits & berceaux', 'Kabann & bèso', 'Cribs & bassinets', 30),
  ('materyel-bebe', 'chez-wo', 'Chaises hautes', 'Chèz wo', 'High chairs', 40),
  ('materyel-bebe', 'pot-bebe', 'Porte-bébés', 'Pòt-bebe', 'Baby carriers', 50),
  ('materyel-bebe', 'pak-bebe', 'Parcs', 'Pak bebe', 'Playpens', 60),
  ('materyel-bebe', 'tapi-evey', 'Tapis d''éveil', 'Tapi evèy', 'Play mats', 70),
  ('jwet', 'jwet-evey', 'Jouets d''éveil', 'Jwèt evèy', 'Baby toys', 10),
  ('jwet', 'jwet-edikatif', 'Jouets éducatifs', 'Jwèt edikatif', 'Educational toys', 20),
  ('jwet', 'poupe', 'Poupées', 'Poupe', 'Dolls', 30),
  ('jwet', 'machin-sikwi', 'Voitures & circuits', 'Machin & sikwi', 'Cars & tracks', 40),
  ('jwet', 'jwet-deyo', 'Jeux d''extérieur', 'Jwèt deyò', 'Outdoor toys', 50),
  ('jwet', 'pelich', 'Peluches', 'Pelich', 'Plush toys', 60),
  ('jwet', 'jwet-konstriksyon', 'Jeux de construction', 'Jwèt konstriksyon', 'Building sets', 70),
  ('atizana-ayisyen', 'fe-dekoupe', 'Fer découpé', 'Fè dekoupe', 'Cut metal art', 10),
  ('atizana-ayisyen', 'bwa-skilte', 'Bois sculpté', 'Bwa skilte', 'Carved wood', 20),
  ('atizana-ayisyen', 'vannri-pay', 'Vannerie & paille', 'Vannri & pay', 'Basketry & straw', 30),
  ('atizana-ayisyen', 'papye-mache', 'Papier mâché', 'Papye mache', 'Papier-mâché', 40),
  ('atizana-ayisyen', 'woch-kon', 'Pierre & corne', 'Wòch & kòn', 'Stone & horn', 50),
  ('atizana-ayisyen', 'twal-atizanal', 'Textiles artisanaux', 'Twal atizanal', 'Artisan textiles', 60),
  ('atizana-ayisyen', 'potri', 'Poterie', 'Potri', 'Pottery', 70),
  ('tablo-atizay', 'penti-ayisyen', 'Peintures haïtiennes', 'Penti ayisyen', 'Haitian paintings', 10),
  ('tablo-atizay', 'eskilti', 'Sculptures', 'Eskilti', 'Sculptures', 20),
  ('tablo-atizay', 'fotografi-atizay', 'Photographies d''art', 'Fotografi atizay', 'Art photography', 30),
  ('tablo-atizay', 'kad-tablo', 'Cadres', 'Kad tablo', 'Frames', 40),
  ('kado-fet', 'dekorasyon-fet', 'Décoration de fête', 'Dekorasyon fèt', 'Party decorations', 10),
  ('kado-fet', 'blad', 'Ballons', 'Blad', 'Balloons', 20),
  ('kado-fet', 'anbalaj-kado', 'Emballages cadeaux', 'Anbalaj kado', 'Gift wrap', 30),
  ('kado-fet', 'kat-kado', 'Cartes', 'Kat kado', 'Cards', 40),
  ('kado-fet', 'kofre-kado', 'Coffrets', 'Kofrè kado', 'Gift boxes', 50),
  ('kado-fet', 'atik-maryaj', 'Articles de mariage', 'Atik maryaj', 'Wedding supplies', 60),
  ('enstriman-mizik', 'tanbou', 'Tambours', 'Tanbou', 'Drums', 10),
  ('enstriman-mizik', 'gita', 'Guitares', 'Gita', 'Guitars', 20),
  ('enstriman-mizik', 'klavye-mizik', 'Claviers', 'Klavye mizik', 'Keyboards', 30),
  ('enstriman-mizik', 'pekisyon', 'Percussions', 'Pèkisyon', 'Percussion', 40),
  ('enstriman-mizik', 'akseswa-mizik', 'Accessoires musique', 'Akseswa mizik', 'Music accessories', 50),
  ('pwodwi-dijital', 'e-book', 'E-books', 'E-book', 'E-books', 10),
  ('pwodwi-dijital', 'fomasyon-kou', 'Formations & cours', 'Fòmasyon & kou', 'Courses & training', 20),
  ('pwodwi-dijital', 'template-model', 'Templates & modèles', 'Template & modèl', 'Templates', 30),
  ('pwodwi-dijital', 'mizik-son', 'Musique & sons', 'Mizik & son', 'Music & sounds', 40),
  ('pwodwi-dijital', 'foto-ilistrasyon', 'Photos & illustrations', 'Foto & ilistrasyon', 'Photos & illustrations', 50),
  ('pwodwi-dijital', 'lojisyel', 'Logiciels', 'Lojisyèl', 'Software', 60),
  ('sevis-pwofesyonel', 'design-grafik', 'Design graphique', 'Design grafik', 'Graphic design', 10),
  ('sevis-pwofesyonel', 'marketing-rezo-sosyal', 'Marketing & réseaux sociaux', 'Marketing & rezo sosyal', 'Marketing & social media', 20),
  ('sevis-pwofesyonel', 'devlopman-web', 'Développement web', 'Devlopman web', 'Web development', 30),
  ('sevis-pwofesyonel', 'foto-videyo', 'Photo & vidéo', 'Foto & videyo', 'Photo & video', 40),
  ('sevis-pwofesyonel', 'tradiksyon', 'Traduction', 'Tradiksyon', 'Translation', 50),
  ('sevis-pwofesyonel', 'kou-patikilye', 'Cours particuliers', 'Kou patikilye', 'Tutoring', 60),
  ('sevis-pwofesyonel', 'kontablite', 'Comptabilité', 'Kontablite', 'Accounting', 70),
  ('sevis-pwofesyonel', 'evenmansyel', 'Événementiel', 'Evenmansyèl', 'Events', 80)
  ) as v(parent, slug, fr, kr, en, pos)
  join p on p.slug = v.parent
on conflict (slug) do nothing;

-- ── Post-conditions ─────────────────────────────────────────────────────────
do $$
declare v_n3 integer; v_actifs_avant integer;
begin
  select count(*) into v_n3 from zabelie_categories where level = 3;
  -- Plancher : le seed complet doit porter le niveau 3 au-delà de 450 lignes (468 semées ici).
  -- Un `on conflict` qui avalerait le seed en masse (collisions de slugs)
  -- casserait ici au lieu de passer en silence.
  if v_n3 < 450 then
    raise exception '0077: niveau 3 à % lignes — seed avalé ?', v_n3;
  end if;
  -- AUCUNE activation par ce seed : le nombre d'actifs niveau 3 reste celui
  -- de la vague 1 (l'activation est un UPDATE d'exploitation, jamais un seed).
  select count(*) into v_actifs_avant from zabelie_categories
   where level = 3 and active;
  if v_actifs_avant > 60 then
    raise exception '0077: % actifs niveau 3 — ce seed ne devait rien activer', v_actifs_avant;
  end if;
end $$;
